security:
  secretToken: 7689098B59776874367639792F423F4528482B4D6251765468576D5A71347438

server:
  port: 8080

spring:
  application:
    name: UserService

  data:
    mongodb:
      uri:  mongodb+srv://deva:deva123@atlascluster.inazn0l.mongodb.net/?retryWrites=true&w=majority&appName=AtlasCluster
      database: TravelBuddy



eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    registry-with-eureka: true
    service-url:
      defaultZone: https://travelbuddy-servicediscovery-production.up.railway.app/eureka/

