security:
  secretToken: 7689098B59776874367639792F423F4528482B4D6251765468576D5A71347438

server:
  port: 8092

spring:
  application:
    name: UserService

    datasource:
      url: jdbc:h2:mem:testdb
      driverClassName: org.h2.Driver
      username: sa
      password: password

#  datasource:
#    url: jdbc:postgresql://Pz1AdozyH4pJiudjM2nmcPL1Rv57fKOc@rain.db.elephantsql.com/tdxhfeep
#    driverClassName: org.postgresql.Driver
#    username: tdxhfeep
#    password: Pz1AdozyH4pJiudjM2nmcPL1Rv57fKOc
#
#  jpa:
#    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    registry-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

